name: Deploy VuePress site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install
          npm list --depth=0
      - name: Debug - Show directory structure
        run: |
          pwd
          ls -R
      - name: Build site
        run: |
          npm run build
        env:
          NODE_ENV: production
      - name: Debug - List build output
        run: ls -R docs/.vuepress/dist
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist